motion_id = fallLeftM
"Switch off all joints


label start
		"		HY		HP		LSP		LSR		LEY		LER		_LWY_		_LH_		RSP		RSR		REY		RER		_RWY_		_RH_		LHYP		LHR		LHP		LKP		LAP		LAR		RHYP		RHR		RHP		RKP		RAP		RAR		Int		Dur
				-20		25		-100	15		200		-20		0			0			50		-21		0.2		15		0			0			0			0		-70		121		-45		40		-			10		-40		80		-40		40		1		100		
				-20		25		-100	15		200		-20		0			0			50		-21		0.2		15		0			0			0			0		-70		121		-45		40		-			10		-40		80		-40		40		1		6000		
				
transition allMotions extern start

